name: dalfox
summary: Powerful open-source XSS scanner and utility focused on automation.
description: |
  Dalfox is a powerful open-source tool that focuses on automation, making it ideal for quickly scanning for XSS flaws and analyzing parameters. 
  Its advanced testing engine and niche features are designed to streamline the process of detecting and verifying vulnerabilities.

adopt-info: ipfs
base: core18
grade: stable
confinement: strict

apps:
  dalfox:
    command: dalfox
    plugs: ["home","network","network-bind"]

parts:
  dalfox:
    source: https://github.com/hahwul/dalfox
    source-tag: main
    plugin: go
    go-channel: 1.24/stable
    go-importpath: github.com/hahwul/dalfox
    build-packages:
        - build-essential