name: Coverage

on:
  push:
    branches: [ main ]
    paths:
      - cmd/**/*
      - pkg/**/*
      - lib/**/*
      - go.mod
      - dalfox.go
      - Dockerfile
  pull_request:
    branches: [ main ]
    paths:
      - cmd/**/*
      - pkg/**/*
      - lib/**/*
      - go.mod
      - dalfox.go
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.23'
      - name: Run coverage
        run: go test -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
