---
  name: Functional Test
  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  jobs:
    test:
      strategy:
        fail-fast: false
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'  # Match your go.mod (check go.mod for exact version)
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1.213.0
          with:
            ruby-version: '3.4'
            bundler-cache: true
            cache-version: 1
        - name: Install Ruby dependencies
          run: bundle install --path vendor/bundle
        - name: Debug environment
          run: pwd && ls -la && ruby -v && bundle exec rake -T
        - name: Run RSpec tests
          run: bundle exec rake test:functional --verbose
          env:
            PATH: "${{ github.workspace }}:$PATH"  # Ensure dalfox binary is in PATH